# fly.toml app configuration file generated for di-bot on 2024-07-28T21:49:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'di-bot'
primary_region = 'ams'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "whatsapp_auth"
destination = "/app/.wwebjs_auth"
