app = 'whatsapp-scheduler'
primary_region = 'ams'

[build]
dockerfile = "Dockerfile"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1

[http_service.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[http_service.checks]]
internal_port = 3000
interval = "15s"
timeout = "2s"
grace_period = "30s"
method = "GET"
path = "/health"
protocol = "http"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[mounts]
source = "whatsapp_auth"
destination = "/app/.wwebjs_auth"

[env]
PORT = "3000"
HOST = "0.0.0.0"
