# fly.toml app configuration file generated for server-twilight-silence-7184 on 2024-08-24T01:17:57+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-twilight-silence-7184'
primary_region = 'ams'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = "whatsapp_auth"
destination = "/app/.wwebjs_auth"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
