app = 'di-bot'
primary_region = 'ams'

[[mounts]]
source = 'whatsapp_auth'
destination = '/app/.wwebjs_auth'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = "connections"
hard_limit = 250
soft_limit = 200

[[http_service.checks]]
interval = "15s"
timeout = "2s"
grace_period = "5s"
method = "GET"
path = "/healthz"
protocol = "http"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[[scheduled_tasks]]
command = "curl http://localhost:3000/healthz"
schedule = "15 7 * * *"
