app = 'whatsapp-scheduler'
primary_region = 'ams'

[build]
dockerfile = "Dockerfile"

[processes]
app = "./prod_start.sh" # Specify the start command

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1

[[http_service.checks]]
interval = "15s"
timeout = "2s"
grace_period = "5s"
method = "GET"
path = "/health"    # Health check endpoint
protocol = "http"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "whatsapp_auth"
destination = "/app/.wwebjs_auth"

[deploy]
strategy = "rolling" # Change to rolling for smoother deployments
max_unavailable = 1

[[services]]
min_machines_running = 1
max_machines_running = 1
