name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build client and prepare server
        run: |
          # Build client
          cd client
          npm install
          npm run build

          # Prepare server
          cd ../server
          npm install
          mkdir -p src/client
          cp -r ../client/dist src/client/

          # Verify content
          ls -R src/client/dist

      - name: Deploy to Fly
        run: |
          cd server
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}